### ISSUE TITLE
Wichtige Frage...

### ISSUE THREAD

**Issue by ghost** [5chufti/HCM_V7#1]
Sehr geehrtes HCM-Team,

ist es möglich Ihren Quellcode im Ganzen oder in Teilen in Programmen zu nutzen, die hier auf GitHub veröffentlicht werden sollen?
Die Software soll unter der MIT-Lizenz veröffentlicht werden.
Wir möchten Ihren Code in folgende Sprachen übersetzen: Fortran, C, C++, Java, Javascript.
Wir haben gute Ideen und möchten diese gerne mit der Öffentlichkeit teilen.
Uns geht es nicht darum, damit Geld zu verdienen - wir möchten nur den HCM-Algorithmus einer größeren Gemeinschaft darbringen.
Unsere Tools hätten auch für Sie einen Mehrwert.

Wie stehen Sie dazu?
Wir warten hoffnungsvoll auf eine positive Nachricht.
Mir freundlichen Grüßen

**Comment by 5chufti** [comment]
Hi,
natürlich steht es ihnen frei das Repo zu klonen, den Code nach ihren Vorstellungen anzupassen (oder in anderen Programmiersprachen zu implementieren) und in Form eines Moduls in ihren Tools zu verwenden, solange der Sourcecode für das Modul ebenfalls veröffentlicht wird. Die LGPL wurde extra gewählt um Kompromisse in Richtung GPL und MIT gewähren zu können. Wichtig ist vor allem, dass die zu Grunde liegende Version für den Benutzer ersichtlich ist und Berechnungen jederzeit mit der Referenzimplementierung (HCM official version) gemacht/verglichen werden können.
Im Prinzip gibt es bereits eine Umsetzung in Java als auch in C#. Diese Versionen sind aber (noch) nicht öffentlich zugänglich. 
Den Hinweis auf FORTRAN verstehe ich jetzt nicht, das ist ja der vorliegende Source.
Gibt es zu den Ideen/Tools schon etwas Greifbares zu sehen?
Mit freundlichen Grüßen,
G.H.
